2025-01-02 21:41:07,141 - managers.model_manager.ModelManager - ERROR - logging_util.py:137 - {"timestamp": "2025-01-02T21:41:07.141844", "error_type": "Exception", "error_message": "Run with UUID 66bdb460e26e47948d9aea1f4df4c1fa is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 22:10:53,982 - managers.model_manager.ModelManager - ERROR - logging_util.py:145 - {"timestamp": "2025-01-02T22:10:53.982756", "error_type": "Exception", "error_message": "Run with UUID d9973fb7953f4bcd8d7e767f4fbbc1cb is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 22:24:35,966 - managers.model_manager.ModelManager - ERROR - logging_util.py:150 - {"timestamp": "2025-01-02T22:24:35.966593", "error_type": "Exception", "error_message": "Run with UUID 2d83d702e0ed436ca5fb32020d18729c is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 22:40:31,926 - managers.model_manager.ModelManager - ERROR - logging_util.py:150 - {"timestamp": "2025-01-02T22:40:31.926615", "error_type": "Exception", "error_message": "Run with UUID bcd6a245a39b4af18dd968caf2c2091a is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 22:54:34,458 - managers.model_manager.ModelManager - ERROR - logging_util.py:150 - {"timestamp": "2025-01-02T22:54:34.458647", "error_type": "Exception", "error_message": "Run with UUID 9a6cb6bc676c43a38e95301960005da9 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 22:59:02,305 - managers.model_manager.ModelManager - ERROR - logging_util.py:150 - {"timestamp": "2025-01-02T22:59:02.305316", "error_type": "Exception", "error_message": "Run with UUID 900834c009fa45199094604c8477aa5c is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 23:08:57,409 - managers.model_manager.ModelManager - ERROR - logging_util.py:150 - {"timestamp": "2025-01-02T23:08:57.409210", "error_type": "Exception", "error_message": "Run with UUID aa62f81ba9d9420a9b92e1d294ed33bc is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 23:33:46,801 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-02T23:33:46.801712", "error_type": "Exception", "error_message": "Run with UUID 7a502e852af54098b8e5d1a338258d9d is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 23:43:37,239 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-02T23:43:37.239928", "error_type": "Exception", "error_message": "Run with UUID e8597205981c46c0bc187692af6c37fe is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-02 23:55:11,941 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-02T23:55:11.941815", "error_type": "Exception", "error_message": "Run with UUID fbca093b7a064edf8c38d113574a75dc is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:01:22,550 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:01:22.550279", "error_type": "Exception", "error_message": "Run with UUID 34a20ed4b0eb470482aab7f53ea10a4b is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:15:13,547 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:15:13.547012", "error_type": "Exception", "error_message": "Run with UUID 09c9d6fa5d5f49fea1827925ba29c128 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:23:52,050 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:23:52.050250", "error_type": "Exception", "error_message": "Run with UUID 6a9b91a64efe492a95048297b168eb62 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:27:07,926 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:27:07.926187", "error_type": "Exception", "error_message": "Run with UUID 02b47155891e4099a567bd1fab45dca3 is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:30:41,635 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:30:41.635320", "error_type": "TypeError", "error_message": "Object of type Tensor is not JSON serializable", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:35:30,261 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:35:30.261869", "error_type": "TypeError", "error_message": "Object of type Tensor is not JSON serializable", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:39:28,329 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:39:28.329482", "error_type": "TypeError", "error_message": "Object of type Tensor is not JSON serializable", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 00:48:19,144 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T00:48:19.144368", "error_type": "TypeError", "error_message": "Object of type Tensor is not JSON serializable", "class": "ModelManager", "context": {"name": "test_model", "type": "nn", "source": "local"}}
2025-01-03 01:52:25,604 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T01:52:25.604469", "error_type": "Exception", "error_message": "Run with UUID 22ab08534b404108901456c414b75fda is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "integrated_model", "type": "nn", "source": "local"}}
2025-01-03 02:00:46,899 - managers.model_manager.ModelManager - ERROR - logging_util.py:159 - {"timestamp": "2025-01-03T02:00:46.898956", "error_type": "Exception", "error_message": "Run with UUID f839d88437fd47fe8095b9ee8b2feded is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True", "class": "ModelManager", "context": {"name": "integrated_model", "type": "nn", "source": "local"}}
